### ISSUE TITLE
FacebookTokenError

### ISSUE THREAD

**Issue by ManasJayanth** [hackintoshrao/express-passport-facebook-Authentication#1]
Express
500 FacebookTokenError: Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request

**Comment by hackintoshrao** [comment]
![screenshot from 2013-11-24 09 55 31](https://f.cloud.github.com/assets/2609511/1608022/8b890cbc-54c0-11e3-865d-66e776cfd3bd.png)
Its working fine over here , i think  the issue is with the version of the modules used , i'll check out a make an appropriate package.json

**Comment by ManasJayanth** [comment]
Error now:

```
FacebookTokenError: This authorization code has been used.
```
